# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1081, 770)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 40, 381, 41))
        font = QtGui.QFont()
        font.setFamily("微软简隶书")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 85, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(590, 190, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微软简行楷")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(19, 30, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(590, 220, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微软简行楷")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(19, 30, 255);")
        self.label_3.setObjectName("label_3")
        self.label_tishi = QtWidgets.QLabel(self.centralwidget)
        self.label_tishi.setGeometry(QtCore.QRect(10, 700, 591, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_tishi.setFont(font)
        self.label_tishi.setStyleSheet("color: rgb(85, 0, 127);")
        self.label_tishi.setObjectName("label_tishi")
        self.pushButton_conn = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_conn.setGeometry(QtCore.QRect(600, 570, 151, 141))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(20)
        self.pushButton_conn.setFont(font)
        self.pushButton_conn.setStyleSheet("")
        self.pushButton_conn.setObjectName("pushButton_conn")
        self.pushButton_save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save.setGeometry(QtCore.QRect(760, 620, 131, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setObjectName("pushButton_save")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(590, 250, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微软简行楷")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(19, 30, 255);")
        self.label_5.setObjectName("label_5")
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(900, 570, 141, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_import = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_import.setGeometry(QtCore.QRect(900, 620, 141, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.pushButton_import.setFont(font)
        self.pushButton_import.setObjectName("pushButton_import")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(760, 50, 291, 141))
        font = QtGui.QFont()
        font.setFamily("微软简行楷")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("color: rgb(19, 30, 255);")
        self.groupBox.setObjectName("groupBox")
        self.radioButton_yaya = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_yaya.setGeometry(QtCore.QRect(30, 110, 261, 31))
        font = QtGui.QFont()
        font.setFamily("微软简行楷")
        font.setPointSize(12)
        self.radioButton_yaya.setFont(font)
        self.radioButton_yaya.setObjectName("radioButton_yaya")
        self.radioButton_man = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_man.setGeometry(QtCore.QRect(30, 30, 115, 41))
        font = QtGui.QFont()
        font.setFamily("微软简行楷")
        font.setPointSize(12)
        self.radioButton_man.setFont(font)
        self.radioButton_man.setChecked(False)
        self.radioButton_man.setObjectName("radioButton_man")
        self.radioButton_xiaoyou = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_xiaoyou.setGeometry(QtCore.QRect(30, 80, 281, 41))
        font = QtGui.QFont()
        font.setFamily("微软简行楷")
        font.setPointSize(12)
        self.radioButton_xiaoyou.setFont(font)
        self.radioButton_xiaoyou.setObjectName("radioButton_xiaoyou")
        self.radioButton_woman = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_woman.setGeometry(QtCore.QRect(30, 60, 115, 31))
        font = QtGui.QFont()
        font.setFamily("微软简行楷")
        font.setPointSize(12)
        self.radioButton_woman.setFont(font)
        self.radioButton_woman.setChecked(True)
        self.radioButton_woman.setObjectName("radioButton_woman")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(590, 50, 121, 111))
        font = QtGui.QFont()
        font.setFamily("微软简行楷")
        font.setPointSize(14)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setStyleSheet("color: rgb(35, 186, 255);\n"
"color: rgb(19, 30, 255);")
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_en = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_en.setGeometry(QtCore.QRect(30, 38, 115, 31))
        font = QtGui.QFont()
        font.setFamily("微软简行楷")
        font.setPointSize(12)
        self.radioButton_en.setFont(font)
        self.radioButton_en.setObjectName("radioButton_en")
        self.radioButton_ch = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_ch.setGeometry(QtCore.QRect(30, 60, 115, 31))
        font = QtGui.QFont()
        font.setFamily("微软简行楷")
        font.setPointSize(12)
        self.radioButton_ch.setFont(font)
        self.radioButton_ch.setChecked(True)
        self.radioButton_ch.setObjectName("radioButton_ch")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(590, 150, 171, 41))
        font = QtGui.QFont()
        font.setFamily("微软简行楷")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(19, 30, 255);")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(940, 220, 31, 20))
        font = QtGui.QFont()
        font.setFamily("微软简隶书")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(940, 250, 31, 16))
        font = QtGui.QFont()
        font.setFamily("微软简行楷")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(920, 200, 31, 20))
        font = QtGui.QFont()
        font.setFamily("微软简行楷")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalSlider_pit = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_pit.setGeometry(QtCore.QRect(660, 230, 271, 19))
        self.horizontalSlider_pit.setMaximum(9)
        self.horizontalSlider_pit.setPageStep(1)
        self.horizontalSlider_pit.setProperty("value", 5)
        self.horizontalSlider_pit.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pit.setObjectName("horizontalSlider_pit")
        self.horizontalSlider_spd = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_spd.setGeometry(QtCore.QRect(660, 260, 271, 19))
        self.horizontalSlider_spd.setMinimum(2)
        self.horizontalSlider_spd.setMaximum(9)
        self.horizontalSlider_spd.setPageStep(1)
        self.horizontalSlider_spd.setProperty("value", 5)
        self.horizontalSlider_spd.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_spd.setObjectName("horizontalSlider_spd")
        self.horizontalSlider_vol = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_vol.setGeometry(QtCore.QRect(660, 200, 271, 19))
        self.horizontalSlider_vol.setMaximum(15)
        self.horizontalSlider_vol.setPageStep(1)
        self.horizontalSlider_vol.setProperty("value", 5)
        self.horizontalSlider_vol.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_vol.setObjectName("horizontalSlider_vol")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(950, 250, 31, 16))
        font = QtGui.QFont()
        font.setFamily("微软简行楷")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(950, 200, 31, 20))
        font = QtGui.QFont()
        font.setFamily("微软简行楷")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(950, 220, 31, 20))
        font = QtGui.QFont()
        font.setFamily("微软简隶书")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.textEdit_input = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_input.setGeometry(QtCore.QRect(20, 110, 551, 591))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.textEdit_input.setFont(font)
        self.textEdit_input.setOverwriteMode(False)
        self.textEdit_input.setObjectName("textEdit_input")
        self.textEdit_output = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_output.setGeometry(QtCore.QRect(600, 300, 461, 251))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.textEdit_output.setFont(font)
        self.textEdit_output.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.textEdit_output.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.textEdit_output.setReadOnly(True)
        self.textEdit_output.setOverwriteMode(False)
        self.textEdit_output.setObjectName("textEdit_output")
        self.pushButton_quit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_quit.setGeometry(QtCore.QRect(900, 670, 141, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.pushButton_quit.setFont(font)
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.pushButton_connmany = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_connmany.setGeometry(QtCore.QRect(760, 670, 131, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.pushButton_connmany.setFont(font)
        self.pushButton_connmany.setObjectName("pushButton_connmany")
        self.pushButton_play = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_play.setGeometry(QtCore.QRect(760, 570, 131, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.pushButton_play.setFont(font)
        self.pushButton_play.setObjectName("pushButton_play")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1081, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_C = QtWidgets.QMenu(self.menubar)
        self.menu_C.setObjectName("menu_C")
        MainWindow.setMenuBar(self.menubar)
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.action_import = QtWidgets.QAction(MainWindow)
        self.action_import.setObjectName("action_import")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.action_conn = QtWidgets.QAction(MainWindow)
        self.action_conn.setObjectName("action_conn")
        self.action_clear = QtWidgets.QAction(MainWindow)
        self.action_clear.setObjectName("action_clear")
        self.action_quit = QtWidgets.QAction(MainWindow)
        self.action_quit.setObjectName("action_quit")
        self.action_help = QtWidgets.QAction(MainWindow)
        self.action_help.setObjectName("action_help")
        self.action_play = QtWidgets.QAction(MainWindow)
        self.action_play.setObjectName("action_play")
        self.action_connmany = QtWidgets.QAction(MainWindow)
        self.action_connmany.setObjectName("action_connmany")
        self.action_register = QtWidgets.QAction(MainWindow)
        self.action_register.setObjectName("action_register")
        self.action_activate = QtWidgets.QAction(MainWindow)
        self.action_activate.setObjectName("action_activate")
        self.menu.addAction(self.action_help)
        self.menu.addSeparator()
        self.menu.addAction(self.action_about)
        self.menu_2.addAction(self.action_conn)
        self.menu_2.addAction(self.action_play)
        self.menu_2.addAction(self.action_save)
        self.menu_2.addAction(self.action_connmany)
        self.menu_2.addAction(self.action_import)
        self.menu_2.addAction(self.action_clear)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action_quit)
        self.menu_C.addAction(self.action_register)
        self.menu_C.addAction(self.action_activate)
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_C.menuAction())

        self.retranslateUi(MainWindow)
        self.horizontalSlider_pit.valueChanged['int'].connect(self.label_6.setNum)
        self.horizontalSlider_spd.valueChanged['int'].connect(self.label_7.setNum)
        self.horizontalSlider_vol.valueChanged['int'].connect(self.label_8.setNum)
        self.pushButton_quit.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "智能语音合成系统"))
        self.label_2.setText(_translate("MainWindow", "音量"))
        self.label_3.setText(_translate("MainWindow", "音调"))
        self.label_tishi.setText(_translate("MainWindow", "已输入0字，还可以输入500字。"))
        self.pushButton_conn.setText(_translate("MainWindow", "合成"))
        self.pushButton_save.setText(_translate("MainWindow", "保存"))
        self.label_5.setText(_translate("MainWindow", "语速"))
        self.pushButton_clear.setText(_translate("MainWindow", "清空内容"))
        self.pushButton_import.setText(_translate("MainWindow", "导入文本"))
        self.groupBox.setTitle(_translate("MainWindow", "发音"))
        self.radioButton_yaya.setText(_translate("MainWindow", "  情感合成 - 度丫丫"))
        self.radioButton_man.setText(_translate("MainWindow", "  男声"))
        self.radioButton_xiaoyou.setText(_translate("MainWindow", "  情感合成 - 度逍遥"))
        self.radioButton_woman.setText(_translate("MainWindow", "  女声"))
        self.groupBox_2.setTitle(_translate("MainWindow", "语言"))
        self.radioButton_en.setText(_translate("MainWindow", "英文"))
        self.radioButton_ch.setText(_translate("MainWindow", "中文"))
        self.label_4.setText(_translate("MainWindow", "输出参数"))
        self.label_6.setText(_translate("MainWindow", "5"))
        self.label_7.setText(_translate("MainWindow", "5"))
        self.label_8.setText(_translate("MainWindow", "5"))
        self.label_9.setText(_translate("MainWindow", "/9"))
        self.label_10.setText(_translate("MainWindow", "/15"))
        self.label_11.setText(_translate("MainWindow", "/9"))
        self.textEdit_input.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#333333; background-color:#ffffff;\">       语音合成是通过机械的、电子的方法产生人造语音的技术。TTS技术隶属于语音合成，它是将计算机自己产生的、或外部输入的文字信息转变为可以听得懂的、流利的汉语口语输出的技术。</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'arial\'; font-size:9pt; color:#333333;\"><br /></p></body></html>"))
        self.pushButton_quit.setText(_translate("MainWindow", "退出"))
        self.pushButton_connmany.setText(_translate("MainWindow", "批量合成"))
        self.pushButton_play.setText(_translate("MainWindow", "播放"))
        self.menu.setTitle(_translate("MainWindow", "帮助(H)"))
        self.menu_2.setTitle(_translate("MainWindow", "文件(F)"))
        self.menu_C.setTitle(_translate("MainWindow", "注册(C)"))
        self.action_about.setText(_translate("MainWindow", "关于...                    "))
        self.action_import.setText(_translate("MainWindow", "导入文本                    "))
        self.action_import.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.action_save.setText(_translate("MainWindow", "保存"))
        self.action_save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_conn.setText(_translate("MainWindow", "合成"))
        self.action_conn.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.action_clear.setText(_translate("MainWindow", "清空内容"))
        self.action_clear.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.action_quit.setText(_translate("MainWindow", "退出"))
        self.action_quit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.action_help.setText(_translate("MainWindow", "使用说明"))
        self.action_play.setText(_translate("MainWindow", "播放"))
        self.action_play.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.action_connmany.setText(_translate("MainWindow", "批量合成"))
        self.action_register.setText(_translate("MainWindow", "注册...            "))
        self.action_activate.setText(_translate("MainWindow", "激活...         "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

